language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash equality_test.sh

notifications: 
  email: 
    on_failure: 
      - always
    on_success: 
      - never
